#!/usr/bin/php
<?php
require __DIR__ . '/vendor/autoload.php';


use Symfony\Component\Console\Application;

// load env values
$fp = fopen('.env', 'r');
while ($option = fgets($fp)) {
    putenv(trim($option));
}

$application = new Application();
$commands = require "kernel.php";
// register commands using kernel file
foreach ($commands as $command) {
    $application->add(new $command);
}
$application->run();